#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         	1
bspc config window_gap           	4

bspc config normal_border_color  	"#000000"
bspc config focused_border_color 	"#8f1fff"
bspc config urgent_border_color  	"#c91220"
bspc config presel_border_color  	"#b6bdca"


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle 	 true


#bspc config pointer_motion_interval 10


#feh --bg-fill /home/cd-r0m/Pictures/wallpapers/astronaut-jellyfish-space-digital-art-uhdpaper.com-hd-107.jpg &
#picom &
#brightnessctl s 100% &
#setxkbmap -layout tr &
$HOME/.config/polybar/launch.sh &
#/usr/bin/dunst &
#/usr/bin/lxpolkit &
#numlockx &
#xset s 0 0 &
#xset dpms 0 0 0 &
#greenclip daemon &
